-- IMPORTANT FOR SHARED HOSTING / PHPMYADMIN:
-- Select your existing database in phpMyAdmin before importing this file.
-- The hosting provider normally does not allow application users to run
-- CREATE DATABASE or USE another database.
-- Recommended database collation: utf8mb4_unicode_ci.
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS registration_room_allocations; DROP TABLE IF EXISTS registration_bus_allocations; DROP TABLE IF EXISTS passengers; DROP TABLE IF EXISTS registrations; DROP TABLE IF EXISTS room_inventory; DROP TABLE IF EXISTS bus_instances; DROP TABLE IF EXISTS itinerary_items; DROP TABLE IF EXISTS room_types; DROP TABLE IF EXISTS travel_options; DROP TABLE IF EXISTS tours; DROP TABLE IF EXISTS admins;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE admins(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE tours(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(200) NOT NULL,location VARCHAR(300) NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,food_charge_per_person DECIMAL(12,2) NOT NULL DEFAULT 0,estimated_misc_expense DECIMAL(12,2) NOT NULL DEFAULT 0,status ENUM('DRAFT','ACTIVE','CLOSED') NOT NULL DEFAULT 'DRAFT',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_tours_status(status,start_date));
CREATE TABLE travel_options(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tour_id BIGINT UNSIGNED NOT NULL,name VARCHAR(150) NOT NULL,mode ENUM('SELF','BUS','OTHER') NOT NULL,charge_type ENUM('PER_PERSON','FIXED') NOT NULL DEFAULT 'PER_PERSON',charge_amount DECIMAL(12,2) NOT NULL DEFAULT 0,capacity INT NULL,is_ac BOOLEAN NOT NULL DEFAULT FALSE,is_active BOOLEAN NOT NULL DEFAULT TRUE,sort_order INT NOT NULL DEFAULT 0,FOREIGN KEY(tour_id) REFERENCES tours(id) ON DELETE CASCADE,INDEX idx_travel_tour(tour_id,is_active));
CREATE TABLE room_types(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tour_id BIGINT UNSIGNED NOT NULL,name VARCHAR(150) NOT NULL,charge_type ENUM('PER_BED','PER_ROOM') NOT NULL,charge_amount DECIMAL(12,2) NOT NULL,capacity INT NOT NULL DEFAULT 1,is_ac BOOLEAN NOT NULL DEFAULT FALSE,extra_bed_allowed BOOLEAN NOT NULL DEFAULT FALSE,extra_bed_charge DECIMAL(12,2) NOT NULL DEFAULT 0,max_extra_beds INT NOT NULL DEFAULT 0,is_active BOOLEAN NOT NULL DEFAULT TRUE,sort_order INT NOT NULL DEFAULT 0,FOREIGN KEY(tour_id) REFERENCES tours(id) ON DELETE CASCADE,INDEX idx_room_tour(tour_id,is_active));
CREATE TABLE bus_instances(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,travel_option_id BIGINT UNSIGNED NOT NULL,bus_number INT NOT NULL,bus_name VARCHAR(100) NOT NULL,capacity INT NOT NULL,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(travel_option_id) REFERENCES travel_options(id) ON DELETE CASCADE,UNIQUE KEY uq_bus_number(travel_option_id,bus_number),INDEX idx_bus_available(travel_option_id,is_active));
CREATE TABLE room_inventory(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,room_type_id BIGINT UNSIGNED NOT NULL,room_number VARCHAR(50) NOT NULL,floor_number VARCHAR(50) NULL,standard_capacity INT NOT NULL,extra_bed_capacity INT NOT NULL DEFAULT 0,is_active BOOLEAN NOT NULL DEFAULT TRUE,notes VARCHAR(255) NULL,FOREIGN KEY(room_type_id) REFERENCES room_types(id) ON DELETE CASCADE,UNIQUE KEY uq_room_number(room_type_id,room_number),INDEX idx_room_available(room_type_id,is_active));
CREATE TABLE itinerary_items(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tour_id BIGINT UNSIGNED NOT NULL,day_number INT NOT NULL,title VARCHAR(200) NOT NULL,location VARCHAR(250),start_time TIME NULL,end_time TIME NULL,notes TEXT,FOREIGN KEY(tour_id) REFERENCES tours(id) ON DELETE CASCADE,INDEX idx_itinerary(tour_id,day_number,start_time));
CREATE TABLE registrations(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tour_id BIGINT UNSIGNED NOT NULL,family_name VARCHAR(180) NOT NULL,contact_name VARCHAR(180) NOT NULL,contact_phone VARCHAR(30) NOT NULL,contact_email VARCHAR(190),travel_option_id BIGINT UNSIGNED NOT NULL,room_type_id BIGINT UNSIGNED NOT NULL,room_units INT NOT NULL DEFAULT 1,extra_beds INT NOT NULL DEFAULT 0,room_number VARCHAR(50) NULL,floor_number VARCHAR(50) NULL,food_amount DECIMAL(12,2) NOT NULL,travel_amount DECIMAL(12,2) NOT NULL,accommodation_amount DECIMAL(12,2) NOT NULL,total_amount DECIMAL(12,2) NOT NULL,amount_received BOOLEAN NOT NULL DEFAULT FALSE,admin_comments VARCHAR(1000) NULL,status ENUM('SUBMITTED','CONFIRMED','CANCELLED') NOT NULL DEFAULT 'SUBMITTED',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(tour_id) REFERENCES tours(id),FOREIGN KEY(travel_option_id) REFERENCES travel_options(id),FOREIGN KEY(room_type_id) REFERENCES room_types(id),UNIQUE KEY uq_tour_family(tour_id,family_name),UNIQUE KEY uq_tour_phone(tour_id,contact_phone),UNIQUE KEY uq_tour_email(tour_id,contact_email),INDEX idx_registration_tour(tour_id,status));
CREATE TABLE passengers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,registration_id BIGINT UNSIGNED NOT NULL,name VARCHAR(180) NOT NULL,gender ENUM('MALE','FEMALE','OTHER') NOT NULL,age INT NOT NULL,FOREIGN KEY(registration_id) REFERENCES registrations(id) ON DELETE CASCADE,INDEX idx_passenger_registration(registration_id));
CREATE TABLE registration_bus_allocations(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,registration_id BIGINT UNSIGNED NOT NULL,bus_instance_id BIGINT UNSIGNED NOT NULL,seats_allocated INT NOT NULL,FOREIGN KEY(registration_id) REFERENCES registrations(id) ON DELETE CASCADE,FOREIGN KEY(bus_instance_id) REFERENCES bus_instances(id),UNIQUE KEY uq_registration_bus(registration_id,bus_instance_id),INDEX idx_bus_usage(bus_instance_id));
CREATE TABLE registration_room_allocations(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,registration_id BIGINT UNSIGNED NOT NULL,room_inventory_id BIGINT UNSIGNED NOT NULL,standard_beds_allocated INT NOT NULL DEFAULT 0,extra_beds_allocated INT NOT NULL DEFAULT 0,FOREIGN KEY(registration_id) REFERENCES registrations(id) ON DELETE CASCADE,FOREIGN KEY(room_inventory_id) REFERENCES room_inventory(id),UNIQUE KEY uq_registration_room(registration_id,room_inventory_id),INDEX idx_room_usage(room_inventory_id));
INSERT INTO tours(name,location,start_date,end_date,food_charge_per_person,estimated_misc_expense,status) VALUES('Nashik Mandir + Igatpuri','Nashik Mandir + Igatpuri','2026-09-26','2026-09-27',1000,0,'ACTIVE');
SET @tour_id=LAST_INSERT_ID();
INSERT INTO travel_options(tour_id,name,mode,charge_type,charge_amount,capacity,is_ac,sort_order) VALUES(@tour_id,'Self','SELF','FIXED',0,NULL,0,1),(@tour_id,'Mandir Planned Bus A','BUS','PER_PERSON',2000,45,1,2);
SET @bus_option_id=(SELECT id FROM travel_options WHERE tour_id=@tour_id AND mode='BUS' LIMIT 1);
INSERT INTO bus_instances(travel_option_id,bus_number,bus_name,capacity) VALUES(@bus_option_id,1,'Bus A',45);
INSERT INTO room_types(tour_id,name,charge_type,charge_amount,capacity,is_ac,extra_bed_allowed,extra_bed_charge,max_extra_beds,sort_order) VALUES(@tour_id,'Non AC','PER_ROOM',1200,4,0,0,0,0,1),(@tour_id,'Dormitory','PER_BED',350,8,0,0,0,0,2),(@tour_id,'AC','PER_ROOM',1500,4,1,1,0,1,3);
SET @nonac4=(SELECT id FROM room_types WHERE tour_id=@tour_id AND name='Non AC');
SET @nonac8=(SELECT id FROM room_types WHERE tour_id=@tour_id AND name='Dormitory');
SET @ac=(SELECT id FROM room_types WHERE tour_id=@tour_id AND name='AC');
INSERT INTO room_inventory(room_type_id,room_number,floor_number,standard_capacity,extra_bed_capacity) VALUES
(@nonac4,'NA4-01','1',4,0),(@nonac4,'NA4-02','1',4,0),(@nonac4,'NA4-03','1',4,0),(@nonac4,'NA4-04','1',4,0),(@nonac4,'NA4-05','1',4,0),(@nonac4,'NA4-06','1',4,0),(@nonac4,'NA4-07','1',4,0),(@nonac4,'NA4-08','1',4,0),(@nonac4,'NA4-09','2',4,0),(@nonac4,'NA4-10','2',4,0),(@nonac4,'NA4-11','2',4,0),(@nonac4,'NA4-12','2',4,0),(@nonac4,'NA4-13','2',4,0),(@nonac4,'NA4-14','2',4,0),(@nonac4,'NA4-15','2',4,0),(@nonac4,'NA4-16','2',4,0),
(@nonac8,'NA8-01','3',8,0),(@nonac8,'NA8-02','3',8,0),(@nonac8,'NA8-03','3',8,0),(@nonac8,'NA8-04','3',8,0),(@nonac8,'NA8-05','3',8,0),(@nonac8,'NA8-06','3',8,0),
(@ac,'AC-01','1',4,1),(@ac,'AC-02','1',4,1),(@ac,'AC-03','1',4,1),(@ac,'AC-04','1',4,1),(@ac,'AC-05','1',4,1),(@ac,'AC-06','1',4,1),(@ac,'AC-07','1',4,1),(@ac,'AC-08','1',4,1),(@ac,'AC-09','1',4,1),(@ac,'AC-10','1',4,1),(@ac,'AC-11','2',4,1),(@ac,'AC-12','2',4,1),(@ac,'AC-13','2',4,1),(@ac,'AC-14','2',4,1),(@ac,'AC-15','2',4,1),(@ac,'AC-16','2',4,1),(@ac,'AC-17','2',4,1),(@ac,'AC-18','2',4,1),(@ac,'AC-19','2',4,1),(@ac,'AC-20','2',4,1),(@ac,'AC-21','3',4,1),(@ac,'AC-22','3',4,1),(@ac,'AC-23','3',4,1),(@ac,'AC-24','3',4,1),(@ac,'AC-25','3',4,1),(@ac,'AC-26','3',4,1),(@ac,'AC-27','3',4,1),(@ac,'AC-28','3',4,1),(@ac,'AC-29','3',4,1),(@ac,'AC-30','3',4,1),(@ac,'AC-31','4',4,1),(@ac,'AC-32','4',4,1),(@ac,'AC-33','4',4,1),(@ac,'AC-34','4',4,1),(@ac,'AC-35','4',4,1),(@ac,'AC-36','4',4,1),(@ac,'AC-37','4',4,1),(@ac,'AC-38','4',4,1),(@ac,'AC-39','4',4,1),(@ac,'AC-40','4',4,1);
INSERT INTO itinerary_items(tour_id,day_number,title,location,start_time,notes) VALUES(@tour_id,1,'Depart Pune','Pune','05:30','Reporting 30 minutes before departure'),(@tour_id,1,'Mandir Darshan','Nashik Mandir','10:30',NULL),(@tour_id,1,'Proceed to Igatpuri','Igatpuri','15:00',NULL),(@tour_id,2,'Morning program','Igatpuri','08:00',NULL),(@tour_id,2,'Return to Pune','Igatpuri','16:00',NULL);
INSERT INTO admins(email,password_hash,is_active) VALUES('admin@gmail.com','$2b$12$SFsbm3rIzszD5Ewqe9sLxur2wD5QXrv5QyQ//0cVaXECaH09bEpgy',1);
